import { type NextPage } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta
					name="description"
					content="Generated by create-t3-app"
				/>
				<link
					rel="icon"
					href="/favicon.ico"
				/>
			</Head>
			<main>
				<div className="container">
					<h1>
						Create <span>T3</span> App
					</h1>
					<AuthShowcase />
				</div>
			</main>
		</>
	);
};

export default Home;

const AuthShowcase: React.FC = () => {
	const { data: sessionData } = useSession();

	return (
		<div>
			<p>{sessionData && <span>Logged in as {sessionData.user.email}</span>}</p>
			<p>{sessionData && <Link href={"/user"}></Link>}</p>
			{!sessionData && (
				<Link href={"/signup"}>
					<button>Sign Up</button>
				</Link>
			)}
			<button
				onClick={sessionData ? () => void signOut() : () => void signIn()}
			>
				{sessionData ? "Sign out" : "Sign in"}
			</button>
		</div>
	);
};
